### ISSUE TITLE
Minimization disrupts water bonds and simulation crashes

### ISSUE THREAD

**Issue by GerardBCN** [Acellera/acemd_issues#9]
The system looks good when loading both pdb and psf, however if I produce 500 minimization steps and save the first run step, two weird long range bonds appear between waters. I'm guessing minimization introduced them there. If I run the simulation for longer it usually becomes unstable around 1000 steps.
[4.zip](https://github.com/Acellera/acemd_issues/files/339009/4.zip)

**Comment by j3mdamas** [comment]
Water 31032

**Comment by j3mdamas** [comment]
I really don't know what to say here. For me it's a non-problem, as I took your protein, re-solvate it, do a minimization and equilibration, and it runs fine.

I do not have access to your system preparation, but I'm guessing that's something wrong going on there. If you can share the system build, we can look into it.

In my opinion, this is pressure problems and that's the reason why the waters start to blow up (hydrogens out of the box).

Unless @mj-harvey thinks otherwise, I would close this.
